'AUTHOR: Cody Redding 
'CONTACT: Codered741@gmail.com

Sub Main()

	SharedVariable("LogVar") = "Smart Part Prop Add"
	iLogicVb.RunExternalRule("Write SV to Log.iLogicVB")
	
	'Init
	Dim oDoc As Document = ThisApplication.ActiveEditDocument
	Dim oCommandMgr as CommandManager = ThisApplication.CommandManager
	
	If oDoc.DocumentType = kDrawingDocumentObject Then
		MessageBox.Show("This rule can only be run in Assemblies and Parts.  Please try again.  ", "Model Only Rule")
		Exit Sub
	End If
	
	oCommandMgr.ControlDefinitions.Item("VaultCheckout").Execute 'Check out file
	
	customPropertySet = oDoc.PropertySets.Item("Inventor User Defined Properties")
	
	Dim TTPropsTxt As New List(Of String)
	Dim TTPropsBool As New List(Of String)
	
	Dim TTParamsIn As New List(Of String)
	Dim TTParamsBool As New List(Of String)
	'Dim TTParamsUL As New List(Of String)
	
	Dim TTParamsOPS As New List(Of String)
	Dim CustomGroupName As String = "TAIT Smart Part"
	Dim pSPVer
	Dim pSP
	Dim VersionNum as String = "2.4"
	
	'Add Values To List
	'String iProperties - for smart part
	TTPropsTxt.Add("DETAILER")
	TTPropsTxt.Add("LENGTH")
	TTPropsTxt.Add("WIDTH")
	TTPropsTxt.Add("THICKNESS")
	TTPropsTxt.Add("MATERIAL NUMBER")
	TTPropsTxt.Add("MATERIAL DESCRIPTION")
	TTPropsTxt.Add("NOTES")
	TTPropsTxt.Add("OPS")
	TTPropsTxt.Add("MakeBuy")
	TTPropsTxt.Add("HasDwg")
	TTPropsTxt.Add("exportPath")
	TTPropsTxt.Add("SPVer")
	TTPropsTxt.Add("LENGTH_mm")
	TTPropsTxt.Add("WIDTH_mm")
	TTPropsTxt.Add("THICKNESS_mm")
	
	'For machining estimation
	' TTPropsTxt.Add("MilledFaceCount")
	' TTPropsTxt.Add("MATERIAL REMOVED")
	' TTPropsTxt.Add("HolesTapped")
	' TTPropsTxt.Add("Holes")
	' TTPropsTxt.Add("Edge Count")
	' TTPropsTxt.Add("Perimeter")
	' TTPropsTxt.Add("RoutTime")
	' TTPropsTxt.Add("MillTime")
	
	'Add Boolean iProperties
	TTPropsBool.Add("SP")

	'Inch Parameters
	TTParamsIn.Add("XDIM")
	TTParamsIn.Add("YDIM")
	TTParamsIn.Add("ZDIM")
	
	'ul Params
	'TTParamsUL.Add("HoleCountTapped")
	'TTParamsUL.Add("HoleCount")

	'Boolean Parameters
	TTParamsBool.Add("MB")
	TTParamsBool.Add("VendorSupplyMtl")
	TTParamsBool.Add("EditPN")
	
	'Operations Parameters
	TTParamsOPS.Add("OP1")
	TTParamsOPS.Add("OP2")
	TTParamsOPS.Add("OP3")
	TTParamsOPS.Add("OP4")
	
	'Main
	'Check that the document Is a model file
	If oDoc.DocumentType = kPartDocumentObject OrElse oDoc.DocumentType = kAssemblyDocumentObject Then
		
		ParamExportCheck(oDoc)
		
		PropAdd(TTPropsTxt, "TXT")
		PropAdd(TTPropsBool, "BOOL")
		ParamAdd(TTParamsIn, "IN", CustomGroupName)
		ParamAdd(TTParamsBool, "BOOL", CustomGroupName)
		'ParamAdd(TTParamsUL, "UL", CustomGroupName)
		OPSMVParamAdd(TTParamsOPS, CustomGroupName)
		
		CustomParamGroup(oDoc, TTParamsBool, CustomGroupName)
		CustomParamGroup(oDoc, TTParamsIn, CustomGroupName)
		CustomParamGroup(oDoc, TTParamsOPS, CustomGroupName)
		
		pSP = customPropertySet.Item("SP")
		pSPVer = customPropertySet.Item("SPVer")
		
		pSPVer.Value = VersionNum
		
		If pSP.Value = False Then
			Parameter("MB") = True
			'TTParamsBool.Add("VendorSupplyMtl") = False
			'Parameter("EditPN") = False
			
			pSP.Value = True
		End If
		
	Else
		MessageBox.Show("Smart Part Config can only be run in a Part or Assembly", "File Type Error")
	End If
	
	Try
		oDoc.ModelingSettings.TappedHoleDiameter = 21764
		'kThreadMajorDiameter = 21761
		'kThreadMinorDiameter = 21762
		'kThreadPitchDiameter = 21763
		'kThreadTapDrillDiameter = 21764
	Catch
		Msgbox("Error setting the tapped hole modeling settings.  ")
	End Try
	
End Sub
	
'''''''''''''''''''''''''Subroutines
Public Sub OPSMVParamAdd(Params As List(Of String), GroupName As String)
	
	Dim OPList As New List(Of String)
	
	OPList.Add(" ")
	OPList.Add("OP009:Lathe CNC~")
	OPList.Add("OP010:Mill CNC~")
	OPList.Add("OP011:Router CNC~")
	OPList.Add("OP012:Mill Manual~")
	OPList.Add("OP013:Lathe Manual~")
	OPList.Add("OP014:Cutting~")
	OPList.Add("OP015:OS - Milling~")
	OPList.Add("OP016:Rolling~")
	'OPList.Add("OP017:Bending~") 'Found to be obsolete 20251020
	OPList.Add("OP020:Paint~")
	OPList.Add("OP022:OS - Turning~")
	OPList.Add("OP023:OS - 2D Laser~")
	OPList.Add("OP024:OS - Waterjetting~")
	'OPList.Add("OP027:CNC Program~") 'obsoleted 20251201 CPR
	OPList.Add("OP031:FAB-MechFabrication")
	OPList.Add("OP034:OS - Forming~")
	OPList.Add("OP035:OS - 3D Laser~")
	OPList.Add("OP036:OS - TIG Welding~")
	OPList.Add("OP038:OS - Turnkey Fabrication~")
	OPList.Add("OP039:OS - Powder Coating~")
	OPList.Add("OP040:OS - Anodizing~")
	OPList.Add("OP041:OS - Injection Molding~")
	OPList.Add("OP060:OS - Misc~")
	OPList.Add("OP061:Softgoods - Fabrication~")
	OPList.Add("OP062:Control – Fabrication~")
	OPList.Add("OP071:OS - 2D Laser & Form~")
	OPList.Add("OP080:OS - Plating~")
	OPList.Add("OP086:OS - Polishing~")
	OPList.Add("OP087:OS - Sandblast~")
	OPList.Add("OP089:OS - Electrical~")
	OPList.Add("OP110:OS - Routing~")
	OPList.Add("OP128:LED Fab~")
	OPList.Add("OP139:3D - Printing~")
	OPList.Add("OP141:OS - Upholstery~")
	'OPList.Add("OP145:Post Processing~") 'obsoleted 20251201 CPR
	OPList.Add("OP146:Laser Cutting / Etching~")
	OPList.Add("OP186:OS - Spray Paint~")
	OPList.Add("OP189:OS - Heat Treat & Destruction~")
	OPList.Add("OP191:OS - Passivate~")
	OPList.Add("OP223:OS - Screenprinting~")
	OPList.Add("OP750:FAB-Quality Control~")
	OPList.Add("OP760:FAB-Weld Inspection~")
	OPList.Add("OP800:MSP-Waterjet~")
	OPList.Add("OP801:MSP-Folding~")
	
	OPList.Sort()
	
	Dim OPx As Parameter
	
	Dim UserParams As UserParameters
	
	Dim oCompDef as Object
	Dim oDoc as Document = ThisApplication.ActiveEditDocument
	
	If oDoc.DocumentType = 12291 Then 'kAssemblyDocumentObject
	'	msgBox("asm")
		oCompDef = CType(oDoc.ComponentDefinition, AssemblyComponentDefinition)
	Else If oDoc.DocumentType = 12290 Then 'kPartDocumentObject
	'	msgbox("part")
		oCompDef = CType(oDoc.ComponentDefinition, PartComponentDefinition)
	End If
	'Dim oCompDef as ComponentDefinition = ThisApplication.ActiveEditDocument.ComponentDefinition
	
	UserParams = oCompDef.Parameters.UserParameters
	' Dim ParamGroup as CustomParameterGroup
	
	' Try
		' ParamGroup = oCompDef.Parameters.CustomParameterGroups.Item(GroupName)
	' Catch
		' ParamGroup = oCompDef.Parameters.CustomParameterGroups.Add(GroupName, GroupName)
	' End Try
	
	For Each pmtr In Params 

		Try 
			param = Parameter.Param(pmtr)
		Catch
			oParameter=UserParams.AddByValue(pmtr, " ", UnitsTypeEnum.kTextUnits)
			' ParamGroup.Add(oParameter)
		End Try
		
		OPx = oCompDef.Parameters.UserParameters.Item(pmtr)
		
		OPx.ExpressionList.ClearAll()
		OPx.ExpressionList.SetExpressionList(OPList.ToArray(), False)	
	
	Next
	
End Sub

Public Sub PropAdd(Props as List(Of String), UnitType As String)
	'Init
	Dim oDoc As Document = ThisApplication.ActiveEditDocument
	customPropertySet = ThisDoc.Document.PropertySets.Item("Inventor User Defined Properties")
	
	For Each prop In Props
		If UnitType = "BOOL" Then
		
			Try
				iprop = customPropertySet.Item(prop)
			Catch
				' Assume error means not found
				customPropertySet.Add("Custom", prop)
				iProperties.Value("Custom", prop) = False
			End Try
			
		Else If UnitType = "TXT"
		
			Try
				iprop = customPropertySet.Item(prop)
			Catch
				' Assume error means not found
				customPropertySet.Add("Custom", prop)
				iProperties.Value("Custom", prop) = ""
			End Try
		
		End If
		
	Next
	
End Sub

Sub ParamAdd(Params As List(Of String), UnitType As String, GroupName As String)
	'Init
	Dim oDoc As Document = ThisApplication.ActiveEditDocument
	
	Dim oCompDef as Object
	
	If oDoc.DocumentType = 12291 Then 'kAssemblyDocumentObject
	'	msgBox("asm")
		oCompDef = CType(oDoc.ComponentDefinition, AssemblyComponentDefinition)
	Else If oDoc.DocumentType = 12290 Then 'kPartDocumentObject
	'	msgbox("part")
		oCompDef = CType(oDoc.ComponentDefinition, PartComponentDefinition)
	End If
	
	'Dim oCompDef As ComponentDefinition = oDoc.ComponentDefinition
	oMyParameter = oCompDef.Parameters.UserParameters
	' Dim ParamGroup as CustomParameterGroup
	
	' Try
		' ParamGroup = oCompDef.Parameters.CustomParameterGroups.Item(GroupName)
	' Catch
		' ParamGroup = oCompDef.Parameters.CustomParameterGroups.Add(GroupName, GroupName)
	' End Try

	'Main
	If UnitType = "BOOL" Then	
		For Each pmtr In Params
			Try
				param = Parameter.Param(pmtr)
			Catch
				oParameter=oMyParameter.AddByValue(pmtr, False, "BOOLEAN")
				' ParamGroup.Add(oParameter)
			End Try
		Next 
	Else If UnitType = "IN" Then
		For Each pmtr In Params
			Try
				param = Parameter.Param(pmtr)
			Catch
				oParameter=oMyParameter.AddByValue(pmtr, 0 in, UnitsTypeEnum.kInchLengthUnits)
				' ParamGroup.Add(oParameter)
			End Try
		Next 
	Else If UnitType = "TXT"
		For Each pmtr In Params
			Try
				param = Parameter.Param(pmtr)
			Catch
				oParameter=oMyParameter.AddByValue(pmtr, " ", UnitsTypeEnum.kTextUnits)
				' ParamGroup.Add(oParameter)
			End Try
		Next 
	Else If UnitType = "UL" Then
		For Each pmtr In Params
			Try
				param = Parameter.Param(pmtr)
			Catch
				oParameter=oMyParameter.AddByValue(pmtr, 0 , UnitsTypeEnum.kUnitlessUnits)
				' ParamGroup.Add(oParameter)
			End Try
		Next 
	End If
End Sub

Sub CustomParamGroup(Doc as Document, Params as List(Of String), GroupName As String)

	Dim oCompDef as Object
	Dim oDoc as Document = ThisApplication.ActiveEditDocument
	
	If oDoc.DocumentType = 12291 Then 'kAssemblyDocumentObject
	'	msgBox("asm")
		oCompDef = CType(oDoc.ComponentDefinition, AssemblyComponentDefinition)
	Else If oDoc.DocumentType = 12290 Then 'kPartDocumentObject
	'	msgbox("part")
		oCompDef = CType(oDoc.ComponentDefinition, PartComponentDefinition)
	End If
	
	'Dim oCompDef as ComponentDefinition = Doc.ComponentDefinition
	
	UserParams = oCompDef.Parameters.UserParameters
	
	Dim ParamGroup As CustomParameterGroup
	
	Try
		ParamGroup = oCompDef.Parameters.CustomParameterGroups.Item(GroupName)
	Catch
		ParamGroup = oCompDef.Parameters.CustomParameterGroups.Add(GroupName, GroupName)
	End Try

	For Each param in Params
		ParamGroup.Add(UserParams.Item(param))
	Next
	
End Sub

Sub ParamExportCheck(doc As Document)

	oCompDef = doc.ComponentDefinition
	
	Try
		oCompDef.Parameters.Item("Length").ExposedAsProperty = False
	Catch
	End Try
	
		Try
		oCompDef.Parameters.Item("WIDTH").ExposedAsProperty = False
	Catch
	End Try
	
	Try
		oCompDef.Parameters.Item("THICKNESS").ExposedAsProperty = False
	Catch
	End Try
	
	Try
		oCompDef.Parameters.Item("LENGTH").ExposedAsProperty = False
	Catch
	End Try
End Sub 'ParamExportCheck